const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Behaviors.Pin,
		C3.Plugins.TiledBg,
		C3.Plugins.Keyboard,
		C3.Behaviors.bound,
		C3.Plugins.Audio,
		C3.Behaviors.scrollto,
		C3.Behaviors.Anchor,
		C3.Plugins.Mouse,
		C3.Plugins.Tilemap,
		C3.Plugins.Spritefont2,
		C3.Plugins.Text,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.TiledBg.Cnds.IsOnScreen,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Audio.Acts.PreloadByName,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Exps.X,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Behaviors.Platform.Acts.SetIgnoreInput,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Behaviors.Platform.Acts.SetMaxSpeed,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Cnds.EveryTick,
		C3.ScriptsInEvents.Fase1_Event24_Act1,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SubVar
	];
};
self.C3_JsPropNameTable = [
	{Solid: 0},
	{chão: 0},
	{Platform: 0},
	{Fixar: 0},
	{MainChar: 0},
	{TiledBackground2: 0},
	{Keyboard: 0},
	{vidaolhomonstro: 0},
	{BoundToLayout: 0},
	{OlhoMonstro: 0},
	{colisao: 0},
	{PlanoDeFundoEmBlocos2: 0},
	{esqueletovida: 0},
	{Plataforma: 0},
	{esqueleto: 0},
	{Audio: 0},
	{ScrollTo: 0},
	{colisor: 0},
	{Âncora: 0},
	{Sprite: 0},
	{PlanoDeFundoEmBlocos: 0},
	{TiledBackground: 0},
	{botao: 0},
	{Mouse: 0},
	{TiledBackground3: 0},
	{Tilemap: 0},
	{TiledBackground4: 0},
	{Tilemap2: 0},
	{arvore1: 0},
	{Sprite2: 0},
	{bossvida: 0},
	{boss: 0},
	{TiledBackground5: 0},
	{SpriteFont: 0},
	{TiledBackground6: 0},
	{sinopse: 0},
	{botaomenu: 0},
	{Text: 0},
	{Text2: 0},
	{Text3: 0},
	{Anchor: 0},
	{Text4: 0},
	{pontuacao: 0},
	{vidaplayer: 0},
	{pontos: 0}
];

self.InstanceType = {
	chão: class extends self.ISpriteInstance {},
	MainChar: class extends self.ISpriteInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	Keyboard: class extends self.IInstance {},
	OlhoMonstro: class extends self.ISpriteInstance {},
	colisao: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos2: class extends self.ITiledBackgroundInstance {},
	esqueleto: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	colisor: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	botao: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	Tilemap: class extends self.ITilemapInstance {},
	TiledBackground4: class extends self.ITiledBackgroundInstance {},
	Tilemap2: class extends self.ITilemapInstance {},
	arvore1: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	boss: class extends self.ISpriteInstance {},
	TiledBackground5: class extends self.ITiledBackgroundInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	TiledBackground6: class extends self.ITiledBackgroundInstance {},
	sinopse: class extends self.ITextInstance {},
	botaomenu: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Text2: class extends self.ITextInstance {},
	Text3: class extends self.ITextInstance {},
	Text4: class extends self.ITextInstance {},
	pontuacao: class extends self.ITextInstance {}
}